name: "Go vulnerabilities Action"
description: "Run the Go vulnerability checker"
author: "opzkit"
inputs:
  packages:
    description: 'Run govulncheck on these packages.'
    required: false
    default: './...'
  go-version-file:
    description: 'Path to the go.mod file.'
    required: false
  go-version:
    description: 'The go version to use when running govulncheck'
    required: false
  check-latest:
    description: 'Set this option to true if you want the action to always check for the latest available version that satisfies the version spec'
    default: false
  govuln-version:
    description: 'The govulncheck version to use whe'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        check-latest: ${{ inputs.check-latest }}
    - name: Get govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@${{ inputs.govuln-version }}
      shell: bash
    - name: Run govulncheck
      run: govulncheck ${{ inputs.packages }}
      shell: bash

branding:
  icon: 'alert-triangle'
  color: 'red'
